version: "3.9"

services:
  main:
    image: bya2/ps-func-site
    ports:
      - target: 3000
        published: 5000
        protocol: tcp
        mode: host
    depends_on:
      - redis
  
  redis:
    image: redis:6.2.6
    volumes:
      - v_redis:/data

volumes:
  v_redis:



